"""
Error code constants for the LipSyncAutomation API
"""


class ErrorCodes:
    """Centralized error code definitions"""

    # General errors
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # File and upload errors
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UPLOAD_FAILED = "UPLOAD_FAILED"

    # Processing errors
    PROCESSING_ERROR = "PROCESSING_ERROR"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_ALREADY_RUNNING = "JOB_ALREADY_RUNNING"

    # Profile errors
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    PROFILE_INVALID = "PROFILE_INVALID"
    PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS"

    # Audio analysis errors
    AUDIO_ANALYSIS_FAILED = "AUDIO_ANALYSIS_FAILED"
    INVALID_AUDIO_FORMAT = "INVALID_AUDIO_FORMAT"
    AUDIO_TOO_SHORT = "AUDIO_TOO_SHORT"

    # Configuration errors
    CONFIG_ERROR = "CONFIG_ERROR"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"

    # System errors
    SYSTEM_OVERLOADED = "SYSTEM_OVERLOADED"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"